### ISSUE TITLE
Syntax Highlighting Error ... or No Error?

### ISSUE THREAD

**Issue by sunnyAfterSnow** [daaain/Handlebars#110]
When I installed the Handlebars package, there was a problem with the syntax highlighting. As shown below. How can I solve it?

**My environment:**
SublimeText win-x64 4143 build (latest fourth edition)
Handlebars package version: 2019.04.13.17.11.43 (the latest version)

![HBS_ERROR](https://github.com/daaain/Handlebars/assets/76153457/8f684839-8c1b-410c-b6a7-5488f94159c4)

Then, strangely enough, when I installed the same package in sublimetext 3, everything worked fine. what is going on?

**My environment:**
SublimeText win-x64 3211 build (latest third version)
Handlebars package version: 2019.04.13.17.11.43 (the latest version)

![HBS_OK](https://github.com/daaain/Handlebars/assets/76153457/883fb24e-2845-416a-88c6-845994f927af)

Conclusion: ST3 and ST4 are not fully compatible, and the same version of the plug-in package will have problems

**Comment by MatthiasPortzel** [comment]
This bug has previously been reported in #109 but there's a lot of unnecessary discussion there so I'm going to pick up here.

TLDR: Use https://tildegit.org/matthias/Sublime-Handlebars 

I've spent a bit of time looking into this. Basically, this syntax includes the JavaScript syntax (with `include: scope:source.js`). I asked in the Discord and @Thom1729 gave this explanation for why this is a problem:
> For context, `- include: scope:source.js` means “whatever the current set of packages associates with the source.js scope, include that”. So that line makes implicit assumptions about other packages outside the control of the Handlebars package. It may be that those assumptions are true about the ST3 JavaScript package but not true about the ST4 JavaScript package.

So my minimum reproduction case is currently as follows:
```yaml
name: Handlebars_Min_Repo
file_extensions:
  - handlebars
  - hbs
scope: text.html.handlebars
contexts:
  main:
    - match: '<works>'
      push:
        - meta_scope: constant.numeric.debug

        - match: '</works>'
          pop: true

    - match: '<doesnt>'
      push:
        - meta_scope: constant.numeric.debug
        - include: scope:source.js

        - match: '</doesnt>'
          pop: true
```

<img width="157" alt="image" src="https://github.com/daaain/Handlebars/assets/19734415/3ea68156-549f-47a2-baa6-51302bb8a26d">

(The image shows that the syntax highlighting fails to pop only after importing the JavaScript scope. I've converted this syntax into .sublime-syntax for this example because it's easier to work with and more clearly demonstrates that this is a behavior issue. I'm not entirely convinced that the above hypothesis is correct; I still think it's possible there's a ST4 bug at the root of this.)

The easy solution at this point is to stop using `include` and to use the modern `embed` directive instead, which was designed to solve *exactly* this problem.

I've taken this step and created a fork that ports the syntax to the modern .sublime-syntax file format and replaces the offending `include` with an `embed`. (On Tildegit instead of GitHub because GitHub has been showing me misleading CoPilot ads when viewing a file.) This does resolve the issue.

https://tildegit.org/matthias/Sublime-Handlebars

This satisfies my immediate need to edit Handlebars files.

The obvious problem with this solution is that it uses a feature of sublime-syntax files which I don't believe is available in .tmLanguage files, and VSCode doesn't support .sublime-syntax files. I haven't checked. So right now, it looks to me like we have to choose between doing nothing and leaving Sublime in a broken state, or moving to modern Sublime features, and potentially forcing VSCode to stay on the current version indefinitely. As a Sublime user, I would prefer the latter option, but I do want to hear from @daaain.
